### ISSUE TITLE
java.io.FileNotFoundException: src\main\static\header_template.html.tmpl 

### ISSUE THREAD

**Issue by hzitoun** [roclas/pomParser#5]
Exception in thread "main" java.io.FileNotFoundException: src\main\static\header_template.html.tmpl 
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.roclas.PomDependencyChecker.printDependencyTree(PomDependencyChecker.java:100)
        at com.roclas.App.main(App.java:31)

**Comment by roclas** [comment]
Could you please check now?
I committed some changes that may fix that problem.
Thank you
